"""init all tables

Revision ID: 56bd6ae6b120
Revises: 82485b5efd01
Create Date: 2025-08-04 14:09:56.266553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bd6ae6b120'
down_revision: Union[str, Sequence[str], None] = '82485b5efd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_table('financial_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_index_code'), 'financial_index', ['code'], unique=True)
    op.create_table('exchange_central_rates',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('currency_id', 'date')
    )
    op.create_index(op.f('ix_exchange_central_rates_currency_id'), 'exchange_central_rates', ['currency_id'], unique=False)
    op.create_index(op.f('ix_exchange_central_rates_date'), 'exchange_central_rates', ['date'], unique=False)
    op.create_table('exchange_market_rates',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('currency_id', 'timestamp', 'source', 'type')
    )
    op.create_index(op.f('ix_exchange_market_rates_currency_id'), 'exchange_market_rates', ['currency_id'], unique=False)
    op.create_index(op.f('ix_exchange_market_rates_source'), 'exchange_market_rates', ['source'], unique=False)
    op.create_index(op.f('ix_exchange_market_rates_timestamp'), 'exchange_market_rates', ['timestamp'], unique=False)
    op.create_table('financial_index_values',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['financial_index.id'], ),
    sa.PrimaryKeyConstraint('index_id', 'timestamp', 'source')
    )
    op.create_index(op.f('ix_financial_index_values_index_id'), 'financial_index_values', ['index_id'], unique=False)
    op.create_index(op.f('ix_financial_index_values_source'), 'financial_index_values', ['source'], unique=False)
    op.create_index(op.f('ix_financial_index_values_timestamp'), 'financial_index_values', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_index_values_timestamp'), table_name='financial_index_values')
    op.drop_index(op.f('ix_financial_index_values_source'), table_name='financial_index_values')
    op.drop_index(op.f('ix_financial_index_values_index_id'), table_name='financial_index_values')
    op.drop_table('financial_index_values')
    op.drop_index(op.f('ix_exchange_market_rates_timestamp'), table_name='exchange_market_rates')
    op.drop_index(op.f('ix_exchange_market_rates_source'), table_name='exchange_market_rates')
    op.drop_index(op.f('ix_exchange_market_rates_currency_id'), table_name='exchange_market_rates')
    op.drop_table('exchange_market_rates')
    op.drop_index(op.f('ix_exchange_central_rates_date'), table_name='exchange_central_rates')
    op.drop_index(op.f('ix_exchange_central_rates_currency_id'), table_name='exchange_central_rates')
    op.drop_table('exchange_central_rates')
    op.drop_index(op.f('ix_financial_index_code'), table_name='financial_index')
    op.drop_table('financial_index')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
